#!/bin/sh

if [ -x /bin/uname ]; then
    system="$(/bin/uname)"
else
    system="$(/usr/bin/uname)"
fi

case "$system" in
Linux)
    prefix=/usr
    triple=x86_64-unknown-linux-gnu
    ;;
FreeBSD)
    prefix=/usr/local
    triple=x86_64-unknown-freebsd
    ;;
*)
    echo "Unknown system: ${system}."
    exit 1
esac

cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target $triple --release
chown -R $USER target Cargo.lock
cp target/$triple/release/wi-fi $prefix/bin
chown root:wheel $prefix/bin/wi-fi
chmod u+s $prefix/bin/wi-fi
