#!/bin/sh

if [ -x /bin/uname ]; then
    system="$(/bin/uname)"
else
    system="$(/usr/bin/uname)"
fi

case "$system" in
Linux)
    prefix=/usr
    ;;
FreeBSD)
    prefix=/usr/local
    ;;
*)
    echo "Unknown system: ${system}."
    exit 1
esac

cargo build --release
cp target/release/wi-fi $prefix/bin
chown root:wheel $prefix/bin/wi-fi
chmod u+s $prefix/bin/wi-fi
