#!/bin/sh
set -eu

cd "$(dirname "$(realpath "$0")")"

./build_release

triple="$(rustc -Vv | awk -F ': ' '{ if($1 == "host") print $2 }')"

chown -R $USER target Cargo.lock
cp target/"$triple"/release/wi-fi /usr/local/bin
chown root:wheel /usr/local/bin/wi-fi
chmod u+s /usr/local/bin/wi-fi
