#!/bin/sh
set -eu

cd "$(dirname "$(realpath "$0")")"

./build_release || exit 1

triple="$(rustc -Vv | awk -F ': ' '{ if($1 == "host") print $2 }')"

chown -R $USER target Cargo.lock || exit 1
cp target/"$triple"/release/wi-fi /usr/local/bin || exit 1
chown root:wheel /usr/local/bin/wi-fi || exit 1
chmod u+s /usr/local/bin/wi-fi || exit 1
