#!/bin/sh

cargo +nightly build \
    -Z build-std=std,panic_abort \
    -Z build-std-features=panic_immediate_abort \
    --target x86_64-unknown-freebsd \
    --release
chown -R $USER target Cargo.lock
cp target/x86_64-unknown-freebsd/release/wi-fi /usr/local/bin
chown root:wheel /usr/local/bin/wi-fi
chmod u+s /usr/local/bin/wi-fi
